# Ubuntu K3s Worker Workflow
#
# This workflow provisions a bare metal machine as a K3s worker node.
# It references the hardware definition and template to install Ubuntu
# and automatically join the K3s cluster.
#
# Usage:
#   1. Create a Hardware definition for the machine
#   2. Copy this workflow and update the hardware reference
#   3. Apply to the cluster: kubectl apply -f workflow.yaml
#   4. Boot the machine from iPXE
#
---
apiVersion: tinkerbell.org/v1alpha1
kind: Workflow
metadata:
  name: provision-worker-01
  namespace: tink-system
  annotations:
    # Security note: Do not commit actual secrets to Git
    # Use SealedSecrets, External Secrets, or similar solution
    security-note: "Use external secret management for sensitive data"
spec:
  # Reference to the hardware definition
  hardwareRef:
    name: worker-01

  # Reference to the template
  templateRef:
    name: ubuntu-24.04-k3s

  # Template variables
  templateParams:
    # Device mapping (from hardware definition)
    device_1: "{{.Hardware.Spec.Disks[0].Device}}"

    # SSH public key for access - Use external secret management in production
    # Example with secret reference: "{{ secret "ssh-public-key" }}"
    ssh_public_key: ""

    # Tailscale auth key for VPN - Use external secret management in production
    # Example with secret reference: "{{ secret "tailscale-auth-key" }}"
    tailscale_auth_key: ""

    # K3s cluster join information - Use external secret management in production
    # Example with secret reference: "{{ secret "k3s-server-url" }}"
    k3s_url: ""
    # Example with secret reference: "{{ secret "k3s-join-token" }}"
    k3s_token: ""
---
# Example: Second worker with secret references (commented for reference)
# apiVersion: tinkerbell.org/v1alpha1
# kind: Workflow
# metadata:
#   name: provision-worker-02
#   namespace: tink-system
# spec:
#   hardwareRef:
#     name: worker-02
#   templateRef:
#     name: ubuntu-24.04-k3s
#   templateParams:
#     device_1: "/dev/sda"
#     # In production, use external secret management:
#     # ssh_public_key: "{{ secret "ssh-public-key" }}"
#     # tailscale_auth_key: "{{ secret "tailscale-auth-key" }}"
#     # k3s_url: "{{ secret "k3s-server-url" }}"
#     # k3s_token: "{{ secret "k3s-join-token" }}"
#     # These would need to be pulled from external secret stores
