# Generated by bootstrap.sh on Fri Nov 28 17:00:48 PST 2025
# OCI Configuration for GitOps Metal Foundry

tenancy_ocid     = "ocid1.tenancy.oc1..aaaaaaaam3t36s4ld4jdjh657x3ecxtdu5csa7xxpcxtpql7dvx2mj473brq"
compartment_ocid = "ocid1.compartment.oc1..aaaaaaaaw4u4o4nyw65ja6l3efpobp7sppe7io6d3tlvvfjicxnc4b3ie7ya"
user_ocid        = "ocid1.user.oc1..aaaaaaaaiigprtijvh5ddzju467nds7deowc3p4c235mv4nzs3yc6ipdgpya"
region           = "us-sanjose-1"

# GitHub for OIDC (informational - auth via API key)
github_owner = "vietcgi"
github_repo  = "gitops-tinkerbell-oci"

# SSH public key for VM access
ssh_public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5/lrhHAQdTRfppzfA7Emn/hcSHobEpl6LzNFsxD9Pi0+sRT8K2shdwZ02vk+eZT3chi6Pwf5Cb82/NS7yLlq4eUxG/IKp1HxVKTdTQgA3E0HF/mmwveCnuR55iUvNNliRyWbBnY/uw5yfhVrDIyAwP+rE16M/ROlorbskJ4R6fFMr4M4o2PjAFL2KH+1lnMrtbNoovqg7/xLBhiDGhs6sNHl4E34PHICkH7Xqkh+7TCDbpjDGxMuNL5RG1zMG1fLFfJX0QIQanN2jHJU2NEMBVWB+BxNYWKWACHQevubER8KdxksBj3Newi65zx2enDoKNE6kpzi2lqPdDpUXwwVf kevin-on-kevin"

# Project name
project_name = "metal-foundry"
