---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: vuabaohiem
spec:
  encryptedData:
    .dockerconfigjson: AgAaCN4ieYMo+rDPFmc8yAq7XEjiIBCq2IMb6Sh/+RAiBa7SxpPVXERYgBWAp9/mmigKajCfJZcjNqXq+1VGmHoyyzDvmNBw8Ljrl1dxFSjVAo1ef8JVXrXQdXrOXnW9mfJNnsxdPpFVPLFG9eNCp6SHVLh2yPpoTgJWAQnBBfflRsyQXPVV6PVnr26EfFvvzEauU3/5G0g78J696HeJ6qIEfacA2+kPa4Odfx7u0kiET8lVI4m0CqxuwTbtBFX9RO4m1NWIN1AXSy9gawD/5LwDAY2vpKf+/6HQebJiXeZl1J9Gx0IyGMlkQZ6ovOgZhY7oNkxhmvD8Jl9CXW6Z4dKtAfNotkZKiB9YZSE8BgJWm647b1FStLu/P4SRfe8FX0tXPDjdDsHkh6W3AOnvOn0i3JNnRXsoEm7TMbWxYVRTiTjpjP/5VZV1oH3SyPWSidaL8F1v221Cm2be0jD9BPMiSXZnKzdzRdZN8iLV8Qd2M/SZX8TJU1UAlQYDEMVZWY+K2DQTYu4WK0ULCFmjy9ikXzcy9OzE/qriZWpcleWN3XPM+cMq2AU3ezxz67Q0yYKMBj35JR8U1ATM40sqUuv0DfLmyt/YULdMr7Q2YM1F2tAqxk00Lux8tDf059DVS/iSCFcLvyJXLl+oc47hKZh4PwtCxbox830OyK9FsBX77Z0xo/2W3KzpsmZLaCVnsDsu691Vz2CpvhKpd1LkQSkf8Pt0dmcXtiAd48NrCUw+QbUUSaErjDihgxRjbL5vhY8rI56lgk96SHU3K8Wvh8N7ancc671YZDydH4NRSxkdaQyGYVsTg3LrQadEnSnvoGStWtE/TSMkD4RV5/WSRVlHanfUTdp1jJqa82xO1RNxTWbu4P3M8Y8YO+4tBKSOPR/ACNhfwEPuCpQKh6wI8/DrCbm0nQHxpgR4Hsg8
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: vuabaohiem
    type: kubernetes.io/dockerconfigjson
