---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: qualityspace
spec:
  encryptedData:
    .dockerconfigjson: AgBNeEsUpvPzSSGwsuj1obwwpNvuyX4KJguwxzwZnKInzV53v4HzWcAscdridj+HQREPLbBYuoPIlG7UChvYBFUt3f0tzys+j5RFR8xF8TyzUWvVXa8xRYsWFr4k24vWcHTcJj0pUfXF3o14f6a2YhfVAszYQYB+6+TfU/iKFbAsSCD0DRJ0e8eWDpJKlR/6RkXTbiQXNN4cGJaC3j2Pa5C6wLVOW+wVmk+K5Fc1iY9wrnpJSqnZ36EjuGpR+rIAiI2KdAD7xgiCuisunPf6ah6rRaOpiamalxZSx2p/yWAmNPeZkzMLQGgaN+DMUaSOC8GiyCt5yMtMT67mao8cV7uza4LiGkP7mNITGFcOGlE+OHG1eYQMCcPpOeq+eCoCXQpeZo56TLbZXLJP3XSckAYPLkudREYVYhBORA6/lE8QAodHeHH56LfhlVDgODFCxWe7t4vx5fQFjMlpIM9Cjnw0o11GmqLykb2mQn0Wb8uetP63hXiZ9ZNaFMevOWr+N9UXhQqC+g4PQ4xR3r8FtHNrItIq915hlgevYwTS2A/s1ut1UTgApNEO/gDOqCQizOXjZtxTiDr4RGTyMF2VaJhIAt7O5hOwt5w8PJweNGQzi/T8VizHEQciA7NTNfoLE2moMmHHtClIuxggcqD4tlEWZ/4A/CDSsHSOdLUdT820Vets1zEjkBEYS2Uwg3uLC8FkU25UlR0Vg7YM2UTgZaCt5bW1YbyuSNazds2XlFX+WGvKvaTitCnlPirXWJxX2YRcIycBv41Rd5VZnFQV5WW3pwu3Agx3wJBUDhm8XRnymEWH1xUG4RHFwQt/Qr65bkQXNltbNWjVK3oU3DeXWyl+TyeDh1dZM8RquZbdf7PxJHdXFQv21EOrtWm/H1pF31PWMT5LefIi9jyxA7WX2RBBbQSVdi3Prrn598mJ
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: qualityspace
    type: kubernetes.io/dockerconfigjson
