apiVersion: v1
kind: Service
metadata:
  name: qualityspace-web
  namespace: qualityspace
  labels:
    app.kubernetes.io/name: qualityspace-web
spec:
  type: ClusterIP
  selector:
    app: qualityspace-web
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
