apiVersion: v1
kind: Service
metadata:
  name: baohiemxe
  namespace: baohiemxe
  labels:
    app.kubernetes.io/name: baohiemxe
spec:
  selector:
    app.kubernetes.io/name: baohiemxe
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: 3200
      protocol: TCP
